---
- hosts: all
  user: all
  tasks:
    - name: download hadoop
      get_url:
        url: https://downloads.apache.org/hadoop/common/hadoop-3.2.1/hadoop-3.2.1.tar.gz
        dest: ~/hadoop-3.2.1.tar.gz
